# Generated by Django 3.1 on 2021-05-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='dsrs',
            new_name='dsr',
        ),
    ]
