# Generated by Django 3.1 on 2021-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0002_auto_20210515_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dsr',
        ),
        migrations.AddField(
            model_name='resource',
            name='dsr',
            field=models.ManyToManyField(related_name='resource', to='dsrs.DSR'),
        ),
    ]
